version: '3'
services:
  client:
    container_name: client
    build: ./client
    tty: true
    volumes:
      - ./client:/usr/src/app
      - ./usr/src/app/node_modules
  server:
    container_name: server
    build: ./server
    tty: true
    volumes:
      - ./server:/usr/src/app
      - ./usr/src/app/node_modules
  nginx:
    container_name: 'nginx'
    image: nginx:stable
    ports: 
      - '3000:80'
    volumes:
      - './etc/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - client
      - server
